// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModuloCadastro.Context;

#nullable disable

namespace ModuloCadastro.Migrations
{
    [DbContext(typeof(ModuloCadastroContext))]
    [Migration("20250605233311_db_05_06_2025")]
    partial class db_05_06_2025
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ModuloCadastro.Entity.AutoNumeradorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdBanco")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdPedidoVenda")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tb_autonumerador");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Financeiro.BancoEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("AgenciaDigito")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("ContaDigito")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("ContaInternacional")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Iban")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Inativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PixChave")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PixTipoChave")
                        .HasColumnType("int");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("TipoConta")
                        .HasColumnType("int");

                    b.Property<string>("TitularDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("TitularNome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tb_bancos");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Produto.CategoriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tb_categoria");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Localizacao.CidadeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Cmunicipio")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Cuf")
                        .HasColumnType("int");

                    b.Property<string>("Dmunicipio")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Cuf");

                    b.ToTable("tb_cidades");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Cliente.ClienteEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime");

                    b.Property<string>("End_bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("End_logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("End_nomeRua")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("End_numero")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Fantasia")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("tb_clientes");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Localizacao.EstadoEntity", b =>
                {
                    b.Property<int>("Cuf")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("Cuf");

                    b.ToTable("tb_estados");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Produto.EstoqueEntity", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("SetorEstoqueId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProdutoId", "SetorEstoqueId");

                    b.HasIndex("SetorEstoqueId");

                    b.ToTable("tb_estoque");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Venda.PedidoVendaEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UsuarioAtualizacaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCriacaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioExclusaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioFechamentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioAtualizacaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.HasIndex("UsuarioExclusaoId");

                    b.HasIndex("UsuarioFechamentoId");

                    b.ToTable("tb_vendas");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Produto.ProdutoEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Cest")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.Property<string>("CodigoEstoque_SKU")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cst_csosn")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Inativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCadastroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("tb_produtos");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Venda.ProdutoVendaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PedidoVendaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SetorEstoqueId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoVendaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("SetorEstoqueId");

                    b.ToTable("tb_produtosvenda");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Venda.RecebimentoVendaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("BancoId")
                        .HasColumnType("int");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DigitoAgencia")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("DigitoContaCorrente")
                        .HasColumnType("varchar(1)");

                    b.Property<int>("Especie")
                        .HasColumnType("int");

                    b.Property<string>("NomeEmissor")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NroDocumento")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NroParcela")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("TotalParcela")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("tb_recebimento_venda");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Produto.SetorEstoqueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tb_setorestoque");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Usuario.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tb_usuarios");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Localizacao.CidadeEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.Cadastro.Localizacao.EstadoEntity", "DadosEstado")
                        .WithMany()
                        .HasForeignKey("Cuf")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DadosEstado");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Cliente.ClienteEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.Cadastro.Localizacao.CidadeEntity", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Produto.EstoqueEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.Cadastro.Produto.ProdutoEntity", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.Cadastro.Produto.SetorEstoqueEntity", "SetorEstoque")
                        .WithMany()
                        .HasForeignKey("SetorEstoqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("SetorEstoque");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Venda.PedidoVendaEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.Cadastro.Cliente.ClienteEntity", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.Cadastro.Usuario.UsuarioEntity", "UsuarioAtualizacao")
                        .WithMany()
                        .HasForeignKey("UsuarioAtualizacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.Cadastro.Usuario.UsuarioEntity", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.Cadastro.Usuario.UsuarioEntity", "UsuarioExclusao")
                        .WithMany()
                        .HasForeignKey("UsuarioExclusaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.Cadastro.Usuario.UsuarioEntity", "UsuarioFechamento")
                        .WithMany()
                        .HasForeignKey("UsuarioFechamentoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioAtualizacao");

                    b.Navigation("UsuarioCriacao");

                    b.Navigation("UsuarioExclusao");

                    b.Navigation("UsuarioFechamento");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Cadastro.Produto.ProdutoEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.Cadastro.Produto.CategoriaEntity", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Venda.ProdutoVendaEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.Venda.PedidoVendaEntity", "PedidoVenda")
                        .WithMany("ListaProdutosVenda")
                        .HasForeignKey("PedidoVendaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.Cadastro.Produto.ProdutoEntity", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.Cadastro.Produto.SetorEstoqueEntity", "SetorEstoque")
                        .WithMany()
                        .HasForeignKey("SetorEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoVenda");

                    b.Navigation("Produto");

                    b.Navigation("SetorEstoque");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.Venda.PedidoVendaEntity", b =>
                {
                    b.Navigation("ListaProdutosVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
