// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModuloCadastro.Context;

#nullable disable

namespace ModuloCadastro.Migrations
{
    [DbContext(typeof(ModuloCadastroContext))]
    partial class ModuloCadastroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ModuloCadastro.Entity.AutoNumeradorEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<int>("idProduto")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tb_autonumerador");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.CategoriaEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("tb_categoria");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.CidadeEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cmunicipio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("cuf")
                        .HasColumnType("int");

                    b.Property<string>("dmunicipio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("tb_cidade");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.ClienteEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataExclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("end_bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("end_cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("end_logradouro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("end_nomeRua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("end_numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("end_uf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("fantasia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("limiteCredito")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("tb_cliente");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.EstadoEntity", b =>
                {
                    b.Property<int>("cuf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("cuf");

                    b.ToTable("tb_estado");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.ProdutoEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("categoria")
                        .HasColumnType("int");

                    b.Property<string>("cest")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("codigoEstoque_SKU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cst_csosn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("estoqueMinimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("idUnidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("inativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ncm")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("origem")
                        .HasColumnType("int");

                    b.Property<int>("setorEstoque")
                        .HasColumnType("int");

                    b.Property<int>("usuarioCadastro")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tb_produtos");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.SetorEstoqueEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("tb_setorestoque");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.UsuarioEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("cargo")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataExclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("tb_usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
