// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModuloCadastro.Context;

#nullable disable

namespace ModuloCadastro.Migrations
{
    [DbContext(typeof(ModuloCadastroContext))]
    partial class ModuloCadastroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ModuloCadastro.Entity.AutoNumeradorEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("idBanco")
                        .HasColumnType("int");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<int>("idPedidoVenda")
                        .HasColumnType("int");

                    b.Property<int>("idProduto")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tb_autonumerador");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.BancoEntity", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("agencia")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("agenciaDigito")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("conta")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("contaDigito")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("contaInternacional")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("iban")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("inativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("pixChave")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("pixTipoChave")
                        .HasColumnType("int");

                    b.Property<string>("swiftCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("tipoConta")
                        .HasColumnType("int");

                    b.Property<string>("titularDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("titularNome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("tb_bancos");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.CategoriaEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("tb_categoria");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.CidadeEntity", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("cmunicipio")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("cuf")
                        .HasColumnType("int");

                    b.Property<string>("dmunicipio")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("cuf");

                    b.ToTable("tb_cidades");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.ClienteEntity", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("dataExclusao")
                        .HasColumnType("datetime");

                    b.Property<string>("end_bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("end_cidade")
                        .HasColumnType("int");

                    b.Property<string>("end_logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("end_nomeRua")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("end_numero")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("end_uf")
                        .HasColumnType("int");

                    b.Property<bool>("excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("fantasia")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("limiteCredito")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("end_cidade");

                    b.ToTable("tb_clientes");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.EstadoEntity", b =>
                {
                    b.Property<int>("cuf")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("cuf");

                    b.ToTable("tb_estados");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.EstoqueEntity", b =>
                {
                    b.Property<int>("idProduto")
                        .HasColumnType("int");

                    b.Property<int>("setorEstoque")
                        .HasColumnType("int");

                    b.Property<decimal>("quantidade")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("idProduto", "setorEstoque");

                    b.HasIndex("setorEstoque");

                    b.ToTable("tb_estoque");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.PedidoVendaEntity", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("dataExclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("dataFechamento")
                        .HasColumnType("datetime");

                    b.Property<bool>("excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<int>("idCriador")
                        .HasColumnType("int");

                    b.Property<int>("usuarioAtualizacao")
                        .HasColumnType("int");

                    b.Property<int>("usuarioFechamento")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idCliente");

                    b.HasIndex("idCriador");

                    b.HasIndex("usuarioAtualizacao");

                    b.HasIndex("usuarioFechamento");

                    b.ToTable("tb_vendas");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.ProdutoEntity", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("categoria")
                        .HasColumnType("int");

                    b.Property<string>("cest")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.Property<string>("codigoEstoque_SKU")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("cst_csosn")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("estoqueMinimo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("idUnidade")
                        .HasColumnType("int");

                    b.Property<bool>("inativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ncm")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<int>("origem")
                        .HasColumnType("int");

                    b.Property<int>("usuarioCadastro")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("categoria");

                    b.ToTable("tb_produtos");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.ProdutoVendaEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DadosProdutoid")
                        .HasColumnType("int");

                    b.Property<int>("idPedido")
                        .HasColumnType("int");

                    b.Property<int>("idProduto")
                        .HasColumnType("int");

                    b.Property<decimal>("quantidade")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.HasIndex("DadosProdutoid");

                    b.HasIndex("idPedido");

                    b.ToTable("tb_produtosvenda");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.SetorEstoqueEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("tb_setorestoque");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.UsuarioEntity", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("cargo")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("dataExclusao")
                        .HasColumnType("datetime");

                    b.Property<bool>("excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("tb_usuarios");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.CidadeEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.EstadoEntity", "DadosEstado")
                        .WithMany()
                        .HasForeignKey("cuf")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DadosEstado");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.ClienteEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.CidadeEntity", "DadosCidade")
                        .WithMany()
                        .HasForeignKey("end_cidade")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DadosCidade");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.EstoqueEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.ProdutoEntity", "DadosProduto")
                        .WithMany()
                        .HasForeignKey("idProduto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.SetorEstoqueEntity", "DadosSetorEstoque")
                        .WithMany()
                        .HasForeignKey("setorEstoque")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DadosProduto");

                    b.Navigation("DadosSetorEstoque");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.PedidoVendaEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.ClienteEntity", "DadosCliente")
                        .WithMany()
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.UsuarioEntity", "DadosUsuarioCriador")
                        .WithMany()
                        .HasForeignKey("idCriador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.UsuarioEntity", "DadosUsuarioAtualizacao")
                        .WithMany()
                        .HasForeignKey("usuarioAtualizacao")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.UsuarioEntity", "DadosUsuarioFechamento")
                        .WithMany()
                        .HasForeignKey("usuarioFechamento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DadosCliente");

                    b.Navigation("DadosUsuarioAtualizacao");

                    b.Navigation("DadosUsuarioCriador");

                    b.Navigation("DadosUsuarioFechamento");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.ProdutoEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.CategoriaEntity", "DadosCategoria")
                        .WithMany()
                        .HasForeignKey("categoria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DadosCategoria");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.ProdutoVendaEntity", b =>
                {
                    b.HasOne("ModuloCadastro.Entity.ProdutoEntity", "DadosProduto")
                        .WithMany()
                        .HasForeignKey("DadosProdutoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModuloCadastro.Entity.PedidoVendaEntity", "DadosPedidoVenda")
                        .WithMany("listaProdutosVenda")
                        .HasForeignKey("idPedido")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DadosPedidoVenda");

                    b.Navigation("DadosProduto");
                });

            modelBuilder.Entity("ModuloCadastro.Entity.PedidoVendaEntity", b =>
                {
                    b.Navigation("listaProdutosVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
